getal = input()
print(int(getal)*1)
print(int(getal)*2)
print(int(getal)*3)
print(int(getal)*4)
print(int(getal)*5)
print(int(getal)*6)
print(int(getal)*7)
print(int(getal)*8)
print(int(getal)*9)
print(int(getal)*10)
